- name: This play will install tree utility
  hosts: all
  become: yes

  vars:
    proxy_conf:
       http_proxy: http://10.19.16.165:8080
       https_proxy: https://10.19.16.165:8080

  tasks:
   - name: Print proxy details 
     debug: var=http_proxy
     with_dict: "{{proxy_conf}}"

   - name: Install tree utility
     apt: name=tree state=present update_cache=yes 
     environment: "{{ proxy_conf }}" 
