---
# handlers file for apache2
- name: Restart apache web server in Ubuntu server
  service: name=apache2 state=restarted
  when: ( ansible_distribution == "Ubuntu" and ansible_os_family == "Debian" )

- name: Restart apache web server in CentOS server
  service: name=httpd state=restarted
  when: ( ansible_distribution == "CentOS" and ansible_os_family == "RedHat" )

