---

- hosts: devserver2 
  become: yes 
  vars:
    proxy_conf:
       http_proxy: http://10.19.16.165:8080
       https_proxy: https://10.19.16.165:8080

  tasks:
   
   - block:
      - name: This task will attempt to install tree on Ubuntu
        apt: name=tree state=present update_cache=yes
        environment: "{{ proxy_conf }}"
   
     rescue:
      - debug: msg="Installing tree utlity with apt failed on {{ ansible_distribution }}"
        ignore_errors: "yes"

      - yum: name=epel-release state=latest
        environment: "{{ proxy_conf }}"

      - yum: name=tree state=latest
        environment: "{{ proxy_conf }}"
       
     always:
      - debug: msg="You will see this message always even if nothing failed."


